---
- name: clean docker
  hosts: all
  become: true
  vars:
    work_directories:
      - /opt/github-runner-2/_work
      - /opt/github-runner/_work
      - /usr/local/share/.cache/yarn
      - /usr/local/share/.cache/yarn/v6

  tasks:
    # Install pip
    - name: install pip
      apt:
        name: python3-pip
        state: present

    # Install docker python module
    - name: install docker python module
      pip:
        name: docker
        state: present

    # Cleanup docker images
    - name: cleanup docker images
      community.docker.docker_prune:
        containers: true
        images: true
        timeout: 600
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true

    # Cleanup _work dirs on the host
    - name: Remove all content from _work directories
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ work_directories }}"

    - name: Recreate empty _work directories
      file:
        path: "{{ item }}"
        state: directory
      loop: "{{ work_directories }}"
