---
- name: clean docker
  hosts: all
  become: true
  tasks:
    - name: cleanup docker images
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
