---
- name: clean docker
  hosts: all
  become: true
  tasks:
    # Install docker python module
    - name: install docker python module
      pip:
        name: docker
        state: present

    # Cleanup docker images
    - name: cleanup docker images
      community.docker.docker_prune:
        containers: true
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
