---
- name: clean docker
  hosts: all
  become: true
  tasks:
    # Install pip
    - name: install pip
      apt:
        name: python3-pip
        state: present

    # Install docker python module
    - name: install docker python module
      pip:
        name: docker
        state: present

    # Cleanup docker images
    - name: cleanup docker images
      community.docker.docker_prune:
        containers: true
        images: true
        timeout: 300
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true

    # Cleanup _work dirs on the host
    - name: find all _work dirs in host
      find:
        paths: /
        patterns: "_work"
        file_type: directory
      register: work_dirs

    - name: remove all content of _work dirs
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ work_dirs.files }}"
