---
- name: clean docker
  hosts: all
  become: true
  tasks:
    # Install pip
    - name: install pip
      apt:
        name: python3-pip
        state: present

    # Install docker python module
    - name: install docker python module
      pip:
        name: docker
        state: present

    # Cleanup docker images
    - name: cleanup docker images
      community.docker.docker_prune:
        containers: true
        images: true
        timeout: 120
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: true
